version: '3'

services:
    php5:
        build: ./docker/php5
        volumes:
            - .:/var/www/salesmatephp:ro
            - ./tmp:/var/testoutput

    php7:
        build: ./docker/php7
        volumes:
            - .:/var/www/salesmatephp:ro
            - ./tmp:/var/testoutput